=== chenglinjava68/baseframe-jproxy/src/main/java/META-INF/baseframe-jproxy-1.0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
   baseframe:jproxy configuration DTD.
   Use the following DOCTYPE

   <!DOCTYPE baseframe:jproxy PUBLIC
    "-//baseframe:jproxy//DTD baseframe:jproxy Configuration 1.0//EN"
    "http://localhost/baseframe-jproxy-1.0.dtd">
-->

<!ELEMENT baseframe:jproxy (properties|registry|service:remote|service:local)*>

<!ELEMENT properties (property)*>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!ELEMENT registry (center)*>
<!ELEMENT center (#PCDATA)>
<!ATTLIST center
    port CDATA #REQUIRED
    host CDATA #REQUIRED
    id CDATA #REQUIRED
>


<!ELEMENT service:remote (rservice)*>
<!ELEMENT rservice (conditions)*>
<!ATTLIST rservice
    class CDATA #REQUIRED
    token CDATA #IMPLIED
    poolsize CDATA #REQUIRED
    version CDATA #IMPLIED
    host CDATA #IMPLIED
    port CDATA #IMPLIED
    center CDATA #IMPLIED
>


<!ELEMENT conditions (condition)*>
<!ELEMENT condition (#PCDATA)>
<!ATTLIST condition
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>


<!ELEMENT service:local (lservice)*>
<!ELEMENT lservice (conditions|whitelist)*>
<!ATTLIST lservice
    class CDATA #REQUIRED
    token CDATA #IMPLIED
    version CDATA #IMPLIED
    center CDATA #IMPLIED
>

<!ELEMENT whitelist (host)*>
<!ELEMENT host (#PCDATA)>

=== chenglinjava68/baseframe-jproxy/src/main/java/jproxy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE baseframe:jproxy PUBLIC
    "-//baseframe:jproxy//DTD baseframe:jproxy Configuration 1.0//EN"
    "http://localhost/baseframe-jproxy-1.0.dtd">
<baseframe:jproxy>
	
	<properties>
		<!-- 本地服务端口 -->
		<property name="local_service_port" value="9999"/>
		<!-- 服务端socket池大小，默认为10-->
		<property name="max_connection" value="10"/>
		<!-- 服务类获取工具，该类由服务端实现 BeanProvider接口-->
		<property name="bean_provider" value="test.beanprovider.TestBeanProvider"/>
	</properties>
	
	<!-- 
	服务注册中心
	可以有多个注册中心，本地的服务可以选择在不同的注册中心注册暴露
	远程服务也可以在不同的注册中心获取服务
	-->
	<registry>
		<center id="localregistry" host="127.0.0.1" port="8888"></center>
	</registry>
	
	<service:remote>
		<rservice class="test.service.TestService"
				 token="123123" poolsize="10" version="1.0" center="localregistry">
			<!-- 条件匹配参数，用于精确匹配服务。
			说明：有些服务接口相同的情况下，不同的机器保存不同的数据，需要获取指定机器的代理服务。
			远程服务将匹配参数暴露给注册中心，客户端请求携带相同的匹配参数就可以动态获取服务。
			 -->
			<conditions>

			</conditions>
		 </rservice>
	</service:remote>
	
	<!--<service:local>
		<lservice class="test.service.TestService" token="123123" version="1.0" center="localregistry">
			&lt;!&ndash; 白名单，只有白名单上匹配的IP地址才能调用 &ndash;&gt;
			<whitelist>
				<host>192.168.*.*</host>
				<host>127.0.0.*</host>
				<host>244.8.56.133</host>
			</whitelist>
			&lt;!&ndash; 条件匹配参数，用于精确匹配服务。
			说明：有些服务接口相同的情况下，不同的机器保存不同的数据，需要获取指定机器的代理服务。
			远程服务将匹配参数暴露给注册中心，客户端请求携带相同的匹配参数就可以动态获取服务。
			 &ndash;&gt;
			<conditions>
				<condition name="dbNum" value="12"/>
			</conditions>
		</lservice>
	</service:local>-->
	
</baseframe:jproxy>
